Repository vanetnuggets/vanetlab-fe, pull requests merged in 2023-04, with the labels that each got.

#48 qol sdn neighbors
  index.html
  src/lib/Canvas/Canvas.svelte
  src/lib/topology/SdnNeighbors.svelte
  src/store/store.js
Labels: enhancement

#49 Update Canvas.svelte
  src/lib/Canvas/Canvas.svelte
Labels: bug

#50 fixed ovs switch deletion when adding nodes to it
  src/lib/Canvas/Canvas.svelte
Labels: bug

#51 better p2p connections, WIP
  index.html
  src/assets/default.css
  src/lib/Canvas/Canvas.svelte
  src/lib/Canvas/TimeManagment.svelte
  src/lib/network/Connections.svelte
  src/lib/topology/SdnNeighbors.svelte
Labels: enhancement

#52 fixed shifted canvas, auto-hide top bar
  src/lib/Canvas/Canvas.svelte
  src/lib/layouts/AppLayout.svelte
  src/lib/layouts/TopBar.svelte
Labels: enhancement

#54 minor changes, transparent bottom bar fix
  public/roads/cross_road.png
  public/roads/horizontal_road.png
  public/roads/vertical_road.png
  src/assets/ap.png
  src/assets/bts.png
  src/lib/Canvas/Canvas.svelte
  src/lib/Canvas/TimeManagment.svelte
  src/lib/layouts/TopBar.svelte
  src/lib/layouts/Welcome.svelte
  src/lib/network/Network.svelte
  src/lib/network/Networks.svelte
Labels: bug

#55 added sdn neighbor lines
  src/lib/Canvas/Canvas.svelte
Labels: enhancement

#56 hf
  src/lib/Canvas/Canvas.svelte
Labels: bug

#58 added icons
  src/assets/node.svg
  src/assets/ovs_node.svg
  src/assets/p2p.svg
  src/lib/Canvas/Canvas.svelte
  src/lib/layouts/Welcome.svelte
Labels: enhancement

#61 connections load & notif refactor
  src/lib/layouts/TopBar.svelte
  src/services/LoadService.js
Labels: bug

#62 Hf5
  src/assets/default.css
  src/lib/network/Connections.svelte
  src/lib/network/Networks.svelte
  src/lib/topology/L2attributes.svelte
  src/lib/topology/L3attributes.svelte
  src/lib/topology/Mobility.svelte
  src/lib/topology/NodeInfo.svelte
  src/lib/topology/SdnController.svelte
  src/lib/topology/SdnNeighbors.svelte
Labels: bug

#64 Pgw
  index.html
  src/assets/edit.svg
  src/assets/favicon.ico
  src/assets/locked.svg
  src/assets/pgw.svg
  src/assets/unlocked.svg
  src/lib/Canvas/Canvas.svelte
  src/lib/layouts/TopBar.svelte
  src/lib/network/Network.svelte
  src/lib/network/Networks.svelte
  src/lib/network/Switch.svelte
  src/lib/topology/L2.svelte
  src/lib/topology/NodeInfo.svelte
  src/store/store.js
Labels: bug

#63 load local scenario
  src/lib/layouts/Welcome.svelte
  src/lib/layouts/welcome/LoadLocal.svelte
Labels: enhancement

#66 Hf6
  src/assets/default.css
  src/lib/Canvas/Canvas.svelte
  src/lib/api/scenarios.js
  src/lib/layouts/MainApp.svelte
  src/lib/layouts/RightDrawer.svelte
  src/lib/layouts/TopBar.svelte
  src/lib/layouts/Welcome.svelte
  src/lib/layouts/welcome/LoadRemote.svelte
  src/lib/network/Connections.svelte
  src/lib/network/Network.svelte
  src/lib/network/Networks.svelte
  src/lib/topology/L2.svelte
  src/store/scenario.js
  src/store/store.js
Labels: bug, enhancement

#65 Golo car
  src/assets/logo.svg
  src/lib/layouts/Logo.svelte
  src/lib/layouts/Welcome.svelte
Labels: enhancement

#70 added cursor coordinates, fixed connection visual types
  src/assets/default.css
  src/lib/Canvas/Canvas.svelte
  src/lib/Canvas/CanvasBar.svelte
  src/lib/Canvas/Coordinates.svelte
  src/lib/Canvas/Iconn.svelte
  src/lib/Canvas/TimeManagment.svelte
  src/lib/Canvas/VisualConnections.svelte
  src/lib/layouts/Welcome.svelte
  src/lib/sipky/sipky.js
  src/store/store.js
Labels: enhancement

#73 Labels
  src/assets/default.css
  src/assets/label.svg
  src/lib/Canvas/Canvas.svelte
  src/lib/Canvas/CanvasBar.svelte
  src/store/scenario.js
Labels: enhancement

#74 added pr template
  .github/pull_request_template.md
Labels: enhancement
